import { useState } from 'react';
import type { Project } from '../types';

interface Props { project: Project | null; }

const MOCK_DOCS = [
  { phase: 'P1', name: 'design_requirements.md', size: '14 KB', date: '2026-03-08' },
  { phase: 'P2', name: 'hardware_requirements_spec.docx', size: '48 KB', date: '2026-03-08' },
  { phase: 'P3', name: 'compliance_report.md', size: '22 KB', date: '2026-03-08' },
  { phase: 'P4', name: 'netlist.json', size: '8 KB', date: '2026-03-08' },
  { phase: 'P6', name: 'glr_specification.md', size: '16 KB', date: '2026-03-08' },
  { phase: 'P8a', name: 'software_requirements.md', size: '30 KB', date: '2026-03-08' },
  { phase: 'P8b', name: 'software_design_doc.md', size: '45 KB', date: '2026-03-08' },
];

export default function Documents({ project }: Props) {
  const [selected, setSelected] = useState<string | null>(null);

  if (!project) {
    return <div style={{ padding: '40px', fontFamily: '"DM Mono", monospace', fontSize: '13px', color: 'var(--text3)', textAlign: 'center' }}>Select a project to view documents.</div>;
  }

  const ext = (name: string) => name.split('.').pop()?.toUpperCase() || 'FILE';
  const extColor = (e: string) => ({ 'MD': 'var(--teal)', 'DOCX': 'var(--blue)', 'JSON': 'var(--warning)' }[e] || 'var(--text3)');

  return (
    <div style={{ display: 'flex', height: '100%' }} className="fade-up">
      {/* Doc List */}
      <div style={{ width: '260px', flexShrink: 0, borderRight: '1px solid var(--border)', padding: '20px 0', overflow: 'auto' }}>
        <div style={{ padding: '0 16px 12px', fontFamily: '"DM Mono", monospace', fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--text3)' }}>Generated Documents</div>
        {MOCK_DOCS.map(doc => (
          <button
            key={doc.name}
            onClick={() => setSelected(doc.name)}
            style={{
              width: '100%', textAlign: 'left', padding: '12px 16px', background: selected === doc.name ? 'rgba(0,198,167,0.08)' : 'none',
              border: 'none', borderLeft: selected === doc.name ? '2px solid var(--teal)' : '2px solid transparent',
              cursor: 'pointer', transition: 'all 0.15s',
            }}
          >
            <div style={{ display: 'flex', gap: '8px', alignItems: 'flex-start' }}>
              <span style={{ fontFamily: '"DM Mono", monospace', fontSize: '9px', padding: '2px 5px', borderRadius: '2px', background: 'var(--panel2)', color: extColor(ext(doc.name)), border: `1px solid ${extColor(ext(doc.name))}`, flexShrink: 0, marginTop: '1px' }}>{ext(doc.name)}</span>
              <div>
                <div style={{ fontFamily: '"DM Mono", monospace', fontSize: '11px', color: selected === doc.name ? 'var(--teal)' : 'var(--text)', lineHeight: 1.4 }}>{doc.name}</div>
                <div style={{ fontFamily: '"DM Mono", monospace', fontSize: '9px', color: 'var(--text4)', marginTop: '2px' }}>{doc.phase} · {doc.size}</div>
              </div>
            </div>
          </button>
        ))}
      </div>

      {/* Preview */}
      <div style={{ flex: 1, padding: '24px', overflow: 'auto' }}>
        {selected ? (
          <div>
            <div style={{ marginBottom: '16px', fontFamily: '"Syne", sans-serif', fontSize: '16px', fontWeight: 700, color: 'var(--text)' }}>{selected}</div>
            <div style={{ background: 'var(--panel)', border: '1px solid var(--border)', borderRadius: '6px', padding: '24px', fontFamily: '"DM Mono", monospace', fontSize: '12px', color: 'var(--text2)', lineHeight: 1.8 }}>
              <div style={{ color: 'var(--teal)', marginBottom: '12px', fontSize: '14px', fontFamily: '"Syne", sans-serif', fontWeight: 700 }}>Document Preview</div>
              <p>This document was generated by the Hardware Pipeline AI. Connect to the FastAPI backend at <code style={{ color: 'var(--teal)' }}>localhost:8001</code> to view the actual document content for project <strong style={{ color: 'var(--text)' }}>{project.name}</strong>.</p>
              <p style={{ marginTop: '12px', color: 'var(--text3)' }}>The full document content will be loaded from the backend file system once the API is connected.</p>
            </div>
          </div>
        ) : (
          <div style={{ textAlign: 'center', paddingTop: '80px', color: 'var(--text3)', fontFamily: '"DM Mono", monospace', fontSize: '13px' }}>
            Select a document from the list to preview it
          </div>
        )}
      </div>
    </div>
  );
}
